# Generated by Django 4.2.13 on 2024-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_portal', '0002_post_description_alter_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_cat',
        ),
        migrations.AddField(
            model_name='post',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
