# Generated by Django 4.2.13 on 2024-06-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_portal', '0003_rename_name_category_name_cat_post_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_cat',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateTimeField(),
        ),
    ]
